/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Car_Dealer;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro Buonerba
 * 24/03/2018
 */
public class Login_Window extends javax.swing.JFrame {
        int a = 0;
    /**
     * Creates new form Login_Window
     */
    public Login_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jBtnSignIn = new javax.swing.JButton();
        jTxtPwd = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Window");
        setBackground(new java.awt.Color(40, 49, 69));
        setMinimumSize(new java.awt.Dimension(991, 532));
        setPreferredSize(new java.awt.Dimension(991, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(991, 532));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setBackground(new java.awt.Color(51, 51, 51));
        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setDividerSize(0);

        jPanel2.setBackground(new java.awt.Color(25, 30, 42));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(852, 533));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 30, 42));
        jPanel3.setForeground(new java.awt.Color(25, 30, 42));
        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 320, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 320, 10));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 129, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 28));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 28));

        jTxtUserName.setBackground(new java.awt.Color(25, 30, 42));
        jTxtUserName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTxtUserName.setForeground(new java.awt.Color(255, 255, 255));
        jTxtUserName.setBorder(null);
        jTxtUserName.setName("jTxtUserName"); // NOI18N
        jTxtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtUserNameFocusLost(evt);
            }
        });
        jPanel3.add(jTxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 320, 40));

        jBtnSignIn.setBackground(new java.awt.Color(97, 212, 195));
        jBtnSignIn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBtnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSignIn.setText("Sign In");
        jBtnSignIn.setBorder(null);
        jBtnSignIn.setName("jBtnSignIn"); // NOI18N
        jBtnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSignInMouseExited(evt);
            }
        });
        jBtnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignInActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 276, 60));

        jTxtPwd.setBackground(new java.awt.Color(25, 30, 42));
        jTxtPwd.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTxtPwd.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPwd.setBorder(null);
        jTxtPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtPwdFocusLost(evt);
            }
        });
        jPanel3.add(jTxtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 320, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 519));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 360, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 300, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Car_Dealer/screen1 - Copy.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, 390, 510));

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Reacting to events (click, ActionPerformed) 
    private void jBtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignInActionPerformed
        // TODO add your handling code here:
        String UserName = jTxtUserName.getText();
        String Pwd = jTxtPwd.getText();
        final String st = "123";
if (a == 3) {
    JOptionPane.showMessageDialog(this, "Since you failed too many times, the program will close");
    dispose();
}
else {
        if ( ! UserName.equals("") & ! Pwd.equals("")) {
            if (UserName.equals("123") &  Pwd.equals("123")){
                //Create new instance of main window and display it.
                Main_Window frm = new Main_Window();
                frm.setVisible(true);
            } else{
                if (a < 3) {
                JOptionPane.showMessageDialog(this,  "Wrong username/password."+"  \nRemaining Attempts: "
                + (3 - a), "Warning" ,JOptionPane.WARNING_MESSAGE );
                
           a++;
        //   System.out.println(a);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this,  "Do not leave the fields empty");
        }
}
    }//GEN-LAST:event_jBtnSignInActionPerformed

    private void jBtnSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSignInMouseEntered
evt.getComponent().setBackground(new Color(217,94,22));
    }//GEN-LAST:event_jBtnSignInMouseEntered

    private void jBtnSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSignInMouseExited
evt.getComponent().setBackground(new Color(97,212,195));
    }//GEN-LAST:event_jBtnSignInMouseExited

    private void jTxtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUserNameFocusGained
     jSeparator4.setBackground(new Color(217,94,22));
     jSeparator4.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtUserNameFocusGained

    private void jTxtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUserNameFocusLost
     jSeparator4.setBackground(Color.WHITE);
     jSeparator4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtUserNameFocusLost

    private void jTxtPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPwdFocusGained
     jSeparator3.setBackground(new Color(217,94,22));
     jSeparator3.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtPwdFocusGained

    private void jTxtPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPwdFocusLost
     jSeparator3.setBackground(Color.WHITE);
     jSeparator3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtPwdFocusLost


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPasswordField jTxtPwd;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables
}
