/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Car_Dealer;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author Alessandro Buonerba
 * 24/03/2018
 */

public class Main_Window extends javax.swing.JFrame {
    //Justify the use of a range of appropriatedata types to store variables andconstants.
    
    //Assigning global and local variables
    //Private because we don't need to access them from other classes
    //final because they will remain unchange throught the program's life span
    //Double because we need to use decimals
    private final Double Stereo_System = 30.50;
    private final Double Leather_Interior = 530.99;
    private final Double GPS = 301.90;
    private final Double Standard = 0.00;
    private final Double Modified = 370.50;
    private final Double Customized_Detailing = 1257.99;
    private Double Trade_In_Allowance = 0.00;
    private Double Tax = 0.00;
    private Double Total = 0.00;
    private Double SubTotal = 0.00;

    //Create new instance of Distance_Converter window and display it.
    private final Distance_Converter frm = new Distance_Converter();
    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnClear = new javax.swing.JButton();
        jBtnPrint = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnCalculate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtp = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTxtBasicPrice = new javax.swing.JTextField();
        jTxtAllowance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtSubTotal = new javax.swing.JTextField();
        jTxtTax = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtAmountDue = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtNames = new javax.swing.JTextField();
        jTxtPostCode = new javax.swing.JTextField();
        jTxtPhone = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jCkBoxStereo = new javax.swing.JCheckBox();
        jCkBoxModified = new javax.swing.JCheckBox();
        jCkBoxLeather = new javax.swing.JCheckBox();
        jCkBoxStandard = new javax.swing.JCheckBox();
        jCkBoxDetailing = new javax.swing.JCheckBox();
        jCkBoxGPS = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConverter = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bespoke Car App");
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Adobe Arabic", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(825, 470));
        setResizable(false);
        setSize(new java.awt.Dimension(80, 100));

        jPanel1.setBackground(new java.awt.Color(25, 30, 42));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(764, 443));
        jPanel1.setMinimumSize(new java.awt.Dimension(764, 443));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClear.setBackground(new java.awt.Color(97, 212, 195));
        jBtnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClear.setText("Clear");
        jBtnClear.setBorder(null);
        jBtnClear.setName("jBtnClear"); // NOI18N
        jBtnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMouseExited(evt);
            }
        });
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 411, 189, 47));

        jBtnPrint.setBackground(new java.awt.Color(97, 212, 195));
        jBtnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnPrint.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPrint.setText("Print");
        jBtnPrint.setBorder(null);
        jBtnPrint.setName("jBtnPrint"); // NOI18N
        jBtnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMouseExited(evt);
            }
        });
        jBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 509, 222, 47));

        jBtnExit.setBackground(new java.awt.Color(97, 212, 195));
        jBtnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExit.setText("Exit");
        jBtnExit.setBorder(null);
        jBtnExit.setName("jBtnExit"); // NOI18N
        jBtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMouseExited(evt);
            }
        });
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 509, 189, 47));

        jBtnCalculate.setBackground(new java.awt.Color(97, 212, 195));
        jBtnCalculate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCalculate.setText("Calculate");
        jBtnCalculate.setBorder(null);
        jBtnCalculate.setName("jBtnCalculate"); // NOI18N
        jBtnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnMouseExited(evt);
            }
        });
        jBtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalculateActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 411, 222, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RECEIPT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtp.setBackground(new java.awt.Color(25, 30, 42));
        jtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 212, 195), 4));
        jtp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtp.setForeground(new java.awt.Color(255, 255, 255));
        jtp.setCaretColor(new java.awt.Color(204, 204, 204));
        jtp.setSelectedTextColor(new java.awt.Color(204, 255, 255));
        jtp.setSelectionColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jtp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 524, 210));

        jPanel4.setBackground(new java.awt.Color(25, 30, 42));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 212, 195), 4, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 232, 190, 10));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Basic Price");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 35, -1, -1));

        jTxtBasicPrice.setBackground(new java.awt.Color(25, 30, 42));
        jTxtBasicPrice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtBasicPrice.setForeground(new java.awt.Color(255, 255, 255));
        jTxtBasicPrice.setText("1");
        jTxtBasicPrice.setBorder(null);
        jTxtBasicPrice.setName("jTxtBasicPrice"); // NOI18N
        jTxtBasicPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtBasicPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtBasicPriceFocusLost(evt);
            }
        });
        jTxtBasicPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KeyRelesed(evt);
            }
        });
        jPanel4.add(jTxtBasicPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 28, 152, 30));

        jTxtAllowance.setBackground(new java.awt.Color(25, 30, 42));
        jTxtAllowance.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtAllowance.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAllowance.setText("0");
        jTxtAllowance.setBorder(null);
        jTxtAllowance.setName("jTxtAllowance"); // NOI18N
        jTxtAllowance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtAllowanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtAllowanceFocusLost(evt);
            }
        });
        jTxtAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAllowanceActionPerformed(evt);
            }
        });
        jTxtAllowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KeyRelesed(evt);
            }
        });
        jPanel4.add(jTxtAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 71, 152, 28));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trade-in-Allowance");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 77, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Subtotal");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jTxtSubTotal.setEditable(false);
        jTxtSubTotal.setBackground(new java.awt.Color(25, 30, 42));
        jTxtSubTotal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTxtSubTotal.setBorder(null);
        jTxtSubTotal.setName("jTxtSubTotal"); // NOI18N
        jPanel4.add(jTxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 177, 188, -1));

        jTxtTax.setEditable(false);
        jTxtTax.setBackground(new java.awt.Color(25, 30, 42));
        jTxtTax.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtTax.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTax.setBorder(null);
        jTxtTax.setName("jTxtTax"); // NOI18N
        jPanel4.add(jTxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 206, 188, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sales Tax");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, -1));

        jTxtAmountDue.setEditable(false);
        jTxtAmountDue.setBackground(new java.awt.Color(25, 30, 42));
        jTxtAmountDue.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtAmountDue.setForeground(new java.awt.Color(255, 102, 0));
        jTxtAmountDue.setBorder(null);
        jTxtAmountDue.setName("jTxtAmountDue"); // NOI18N
        jPanel4.add(jTxtAmountDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 236, 188, 32));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Amount Due");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 202, 190, 10));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 350, 286));

        jPanel2.setBackground(new java.awt.Color(25, 30, 42));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 212, 195), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 224, 260, 10));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, 260, 10));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 144, 260, 10));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 184, 260, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Details:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Names");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Post Code");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 202, -1, -1));

        jTxtNames.setBackground(new java.awt.Color(25, 30, 42));
        jTxtNames.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtNames.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNames.setBorder(null);
        jTxtNames.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtNamesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNamesFocusLost(evt);
            }
        });
        jPanel2.add(jTxtNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 254, -1));

        jTxtPostCode.setBackground(new java.awt.Color(25, 30, 42));
        jTxtPostCode.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtPostCode.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPostCode.setBorder(null);
        jTxtPostCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPostCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtPostCodeFocusLost(evt);
            }
        });
        jPanel2.add(jTxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 254, -1));

        jTxtPhone.setBackground(new java.awt.Color(25, 30, 42));
        jTxtPhone.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtPhone.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPhone.setBorder(null);
        jTxtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtPhoneFocusLost(evt);
            }
        });
        jTxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KeyRelesed(evt);
            }
        });
        jPanel2.add(jTxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 254, -1));

        jTxtAddress.setBackground(new java.awt.Color(25, 30, 42));
        jTxtAddress.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtAddress.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAddress.setBorder(null);
        jTxtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtAddressFocusLost(evt);
            }
        });
        jPanel2.add(jTxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 254, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 390, 286));

        jPanel3.setBackground(new java.awt.Color(25, 30, 42));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 212, 195), 4, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCkBoxStereo.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxStereo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxStereo.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxStereo.setText("Stereo System");
        jCkBoxStereo.setName("jCkBoxStereo"); // NOI18N
        jPanel3.add(jCkBoxStereo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, -1, -1));

        jCkBoxModified.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxModified.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxModified.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxModified.setText("Modified");
        jCkBoxModified.setName("jCkBoxModified"); // NOI18N
        jPanel3.add(jCkBoxModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 110, -1));

        jCkBoxLeather.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxLeather.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxLeather.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxLeather.setText("Leather Interior");
        jCkBoxLeather.setName("jCkBoxLeather"); // NOI18N
        jPanel3.add(jCkBoxLeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, -1, -1));

        jCkBoxStandard.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxStandard.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxStandard.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxStandard.setText("Standard");
        jCkBoxStandard.setName("jCkBoxStandard"); // NOI18N
        jPanel3.add(jCkBoxStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 112, -1, -1));

        jCkBoxDetailing.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxDetailing.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxDetailing.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxDetailing.setText("Customized Detailing");
        jCkBoxDetailing.setName("jCkBoxDetailing"); // NOI18N
        jPanel3.add(jCkBoxDetailing, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 211, -1, -1));

        jCkBoxGPS.setBackground(new java.awt.Color(25, 30, 42));
        jCkBoxGPS.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCkBoxGPS.setForeground(new java.awt.Color(255, 255, 255));
        jCkBoxGPS.setText("GPS");
        jCkBoxGPS.setName("jCkBoxGPS"); // NOI18N
        jPanel3.add(jCkBoxGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACCESSORIES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 164, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 230, 250));

        jMenuBar1.setBackground(new java.awt.Color(25, 30, 42));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jMenuBar1.setForeground(new java.awt.Color(25, 30, 42));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.setOpaque(false);

        jMenuConverter.setBackground(new java.awt.Color(255, 255, 255));
        jMenuConverter.setBorder(null);
        jMenuConverter.setForeground(new java.awt.Color(255, 255, 255));
        jMenuConverter.setText("Distance Converter");
        jMenuConverter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuConverter.setName("jMenuConverter"); // NOI18N
        jMenuConverter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConverterMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuConverter);

        jMenuHelp.setBackground(new java.awt.Color(255, 255, 255));
        jMenuHelp.setBorder(null);
        jMenuHelp.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHelp.setText("Help");
        jMenuHelp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuHelp.setName("jMenuHelp"); // NOI18N
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuConverterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConverterMouseClicked
        // TODO add your handling code here:
                frm.setVisible(true);
    }//GEN-LAST:event_jMenuConverterMouseClicked


    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        //Close App
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:
        //Clear all selected values
               
        //Use of Array and loops.
        //Create an array of textboxes and clear its content while looping through
        JTextField txt[] = {jTxtBasicPrice,jTxtSubTotal,jTxtAmountDue,
                jTxtTax,jTxtAllowance,jTxtNames,jTxtPhone,jTxtPostCode,jTxtAddress};
        for (JTextField txt1 : txt) {
            txt1.setText("");
        }
        jtp.setText("");
        //Create an array of JCheckBox and clear its' check property while looping through
        JCheckBox chbx[] = {jCkBoxDetailing,jCkBoxStereo,jCkBoxStandard,jCkBoxModified,jCkBoxLeather,jCkBoxGPS};
        for (JCheckBox chbx1 : chbx) {
            chbx1.setSelected(false);
        }
    }//GEN-LAST:event_jBtnClearActionPerformed
//Used in jBtnCalculateActionPerformed
    private Double findTax(Double a, Double b)
    {
        return a * b;
    }
    //Calling procedures from other procedures and manipulating dates
    private void jBtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalculateActionPerformed
        // TODO add your handling code here:
        //Getting user inputs
        String st =jTxtBasicPrice.getText();
        String st2 =jTxtAllowance.getText();
                
        try{
            
            //Develop programs using simple and complex conditions to a given specification.
            
                //Check if the user left the value field empty
            if (! st.isEmpty() & ! st2.isEmpty() & ! jTxtNames.getText().isEmpty() & ! jTxtPhone.getText().isEmpty()
                    & ! jTxtPostCode.getText().isEmpty() & ! jTxtAddress.getText().isEmpty()) {
                //Converting to double and assigning values
                SubTotal = Double.parseDouble(st);
                Trade_In_Allowance = Double.parseDouble(st2);
                
                //Checking extra selected features
                if (jCkBoxStereo.isSelected()) {
                    SubTotal += Stereo_System;
                }
                if (jCkBoxDetailing.isSelected()) {
                    SubTotal += Customized_Detailing;
                }
                if (jCkBoxLeather.isSelected()) {
                    SubTotal += Leather_Interior;
                }
                if (jCkBoxGPS.isSelected()) {
                    SubTotal += GPS;
                }
                if (jCkBoxGPS.isSelected()) {
                    SubTotal += Customized_Detailing;
                }
                if (jCkBoxModified.isSelected()) {
                    SubTotal += Modified;
                }
                if (jCkBoxStandard.isSelected()) {
                    SubTotal += Standard;
                }               
                //Set subTotal
                double round = Math.round(SubTotal * 100.0) / 100.0;
                jTxtSubTotal.setText("£" + round);
                        

                //get, set Tax
                //Calling procedures from other procedures and manipulating dates
                Tax= findTax(SubTotal, 0.06);   //Calling procedures.
                
               // st =  String.valueOf(Tax.floatValue());
               round = Math.round(Tax * 100.0) / 100.0;

                jTxtTax.setText("£" + round);
              //  double d1 = Double.parseDouble(jTxtSubTotal.getText());
              //  double roundSub = Math.round(d1 * 100.0) / 100.0;
                
                //get, set Total
                Total = (SubTotal + Tax) - Trade_In_Allowance;
              //  st =  String.valueOf(Math.round(Total * 100.0) / 100.0);
              //  d1 = Double.parseDouble(jTxtAmountDue.getText());
              //  double roundTotal = Math.round(d1 * 100.0) / 100.0;
              
              round = Math.round(Total * 100.0) / 100.0;
                jTxtAmountDue.setText("£" + round);

                jtp.setBackground(new Color(25,30,42));
                jtp.setVisible(true);
                String str;
                str = "Basic Price: \t\t" + "£" + jTxtBasicPrice.getText();
                str += "\n" + "Trade-in-Allowance: \t" +"£" + jTxtAllowance.getText();
                str += "\n" + "Subtotal: \t\t" + jTxtSubTotal.getText();
                str += "\n" + "Tax: \t\t\t" + jTxtTax.getText();
                str += "\n" + "Total: \t\t\t" + jTxtAmountDue.getText();
                str += "\n" + "Name: \t\t\t" + jTxtNames.getText();
                str += "\n" + "Phone: \t\t\t" + jTxtPhone.getText();
                str += "\n" + "Post Code: \t\t" + jTxtPostCode.getText();
                str += "\n" + "Address: \t\t" + jTxtAddress.getText();
                               

                jtp.setText(str); 
            }else      {
            JOptionPane.showMessageDialog(this,  "Empty Value provided");
            }
        }
        catch(Exception ex){
            //Display caught error
            JOptionPane.showMessageDialog(this, "Error performing Operation: " + ex.getMessage());
        }       
    }//GEN-LAST:event_jBtnCalculateActionPerformed
//Reacting to events
    private void jbtnMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMouseEnter
evt.getComponent().setBackground(new Color(217,94,22));
    }//GEN-LAST:event_jbtnMouseEnter
//Reacting to events
    private void jbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMouseExited
evt.getComponent().setBackground(new Color(97,212,195));
    }//GEN-LAST:event_jbtnMouseExited
//Reacting to events
    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
        Help_Window help = new Help_Window();
        help.show();
    }//GEN-LAST:event_jMenuHelpMouseClicked
//Reacting to events
    private void jBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrintActionPerformed
        
        try {
            jtp.print();
        } catch (java.awt.print.PrinterException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBtnPrintActionPerformed

    //Reacting to events
    private void KeyRelesed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyRelesed
        // TODO add your handling code here:
        //Detect and destroy non number values
        if (! Character.isDigit(evt.getKeyChar()) &  evt.getKeyCode()!=KeyEvent.VK_BACKSPACE) {
            evt.consume();
            //If consume does not work, then
            String st;  //Local Variable
            try{
                if (evt.getComponent().getName() == jTxtBasicPrice.getName()) {
                st = jTxtBasicPrice.getText();
                jTxtBasicPrice.setText(st.substring(0,(st.length()- 1)));
               
            }else if (evt.getComponent().getName() == jTxtAllowance.getName()) {
                st = jTxtAllowance.getText();
                jTxtAllowance.setText(st.substring(0,(st.length()- 1)));
               
            }else if (evt.getComponent().getName() == jTxtPhone.getName()) {
                st = jTxtPhone.getText();
                jTxtPhone.setText(st.substring(0,(st.length()- 1)));
            }
            }catch (Exception ex ){
            }
        }
    }//GEN-LAST:event_KeyRelesed

    private void jTxtAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAllowanceActionPerformed

    private void jTxtBasicPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtBasicPriceFocusGained
     jSeparator6.setBackground(new Color(217,94,22));
     jSeparator6.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtBasicPriceFocusGained

    private void jTxtBasicPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtBasicPriceFocusLost
     jSeparator6.setBackground(Color.WHITE);
     jSeparator6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtBasicPriceFocusLost

    private void jTxtAllowanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtAllowanceFocusGained
     jSeparator5.setBackground(new Color(217,94,22));
     jSeparator5.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtAllowanceFocusGained

    private void jTxtAllowanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtAllowanceFocusLost
     jSeparator5.setBackground(Color.WHITE);
     jSeparator5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtAllowanceFocusLost

    private void jTxtNamesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNamesFocusGained
     jSeparator10.setBackground(new Color(217,94,22));
     jSeparator10.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtNamesFocusGained

    private void jTxtNamesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNamesFocusLost
     jSeparator10.setBackground(Color.WHITE);
     jSeparator10.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtNamesFocusLost

    private void jTxtPostCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPostCodeFocusGained
     jSeparator11.setBackground(new Color(217,94,22));
     jSeparator11.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtPostCodeFocusGained

    private void jTxtPostCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPostCodeFocusLost
     jSeparator11.setBackground(Color.WHITE);
     jSeparator11.setForeground(Color.WHITE);        
    }//GEN-LAST:event_jTxtPostCodeFocusLost

    private void jTxtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPhoneFocusGained
     jSeparator12.setBackground(new Color(217,94,22));
     jSeparator12.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtPhoneFocusGained

    private void jTxtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPhoneFocusLost
     jSeparator12.setBackground(Color.WHITE);
     jSeparator12.setForeground(Color.WHITE); 
    }//GEN-LAST:event_jTxtPhoneFocusLost

    private void jTxtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtAddressFocusGained
     jSeparator7.setBackground(new Color(217,94,22));
     jSeparator7.setForeground(new Color(217,94,22));
    }//GEN-LAST:event_jTxtAddressFocusGained

    private void jTxtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtAddressFocusLost
     jSeparator7.setBackground(Color.WHITE);
     jSeparator7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jTxtAddressFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalculate;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnPrint;
    private javax.swing.JCheckBox jCkBoxDetailing;
    private javax.swing.JCheckBox jCkBoxGPS;
    private javax.swing.JCheckBox jCkBoxLeather;
    private javax.swing.JCheckBox jCkBoxModified;
    private javax.swing.JCheckBox jCkBoxStandard;
    private javax.swing.JCheckBox jCkBoxStereo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConverter;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtAllowance;
    private javax.swing.JTextField jTxtAmountDue;
    private javax.swing.JTextField jTxtBasicPrice;
    private javax.swing.JTextField jTxtNames;
    private javax.swing.JTextField jTxtPhone;
    private javax.swing.JTextField jTxtPostCode;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTax;
    private javax.swing.JTextPane jtp;
    // End of variables declaration//GEN-END:variables
}
